version: "3.7"

services:
  project:
    image: sindb/de-pg-cr-af:latest
    ports:
      - "3000:3000"
      - "3002:3002"
      - "15432:5432"
    volumes:
      - D:\Users\shap1\Desktop\DE\proj5\src\dags:/lessons/dags